extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'next/core-web-vitals'

plugins:
  - '@typescript-eslint'
  - 'react'
  - 'react-hooks'
  - 'jsx-a11y'
  - 'import'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2022
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: 'detect'
  import/resolver:
    typescript: true
    node: true

rules:
  # Regras gerais
  'no-console': ['warn', { allow: ['warn', 'error'] }]
  'no-unused-vars': 'off'  # Desligado em favor da versão typescript-eslint
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }]
  'prefer-const': 'warn'
  'no-duplicate-imports': 'error'
  
  # Regras React
  'react/prop-types': 'off'  # Usar TypeScript em vez de PropTypes
  'react/react-in-jsx-scope': 'off'  # Não necessário com Next.js
  'react/jsx-filename-extension': ['warn', { extensions: ['.tsx'] }]
  'react/jsx-no-bind': ['warn', { allowArrowFunctions: true }]
  'react/no-array-index-key': 'warn'
  
  # Regras de hooks
  'react-hooks/rules-of-hooks': 'error'
  'react-hooks/exhaustive-deps': 'warn'
  
  # Regras de importação
  'import/order': ['warn', {
    'groups': [['builtin', 'external'], 'internal', ['parent', 'sibling', 'index']],
    'newlines-between': 'always',
    'alphabetize': { 'order': 'asc', 'caseInsensitive': true }
  }]
  'import/no-default-export': 'off'  # Next.js precisa de default exports
  'import/no-unresolved': 'error'
  
  # Regras de acessibilidade
  'jsx-a11y/alt-text': 'warn'
  'jsx-a11y/aria-props': 'warn'
  'jsx-a11y/anchor-is-valid': 'warn'

# Regras específicas para páginas e componentes
overrides:
  # Regras específicas para páginas Next.js
  - files: ['app/**/page.tsx', 'app/**/layout.tsx']
    rules:
      'import/no-default-export': 'off'  # Páginas Next.js precisam de export default
  
  # Regras para arquivos de teste
  - files: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx']
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
      'no-console': 'off'
