# Configuração para deploy no Cloudflare Workers (alternativa à Vercel)
# Para usar, instale wrangler: npm install -g wrangler
# E execute: wrangler deploy

name = "nova-ipe"
main = ".next/server.js"
compatibility_date = "2025-01-01"

# Configuração de compilação
[build]
command = "npm run build:production"
watch_dir = "app"

# Configuração de assets estáticos
[site]
bucket = ".next/static"
entry-point = ".next/server.js"

# Variáveis de ambiente
[vars]
NEXT_PUBLIC_SKIP_NATIVE_DEPS = "true"

# Configurações de rotas
[[routes]]
pattern = "/*"
zone_name = "nova-ipe.com.br"

# Configuração de cache
[env.production]
workers_dev = false
route = "nova-ipe.com.br/*"

# Configurações avançadas para lidar com build
[build.upload]
format = "service-worker"
