backend:
  name: git-gateway # Utiliza Git Gateway para autenticação sem backend customizado.
  branch: main # A branch que receberá as atualizações.

media_folder: "public/images/uploads" # Pasta para armazenamento de mídias.
public_folder: "/images/uploads" # Caminho público para acessar as mídias.

collections:
  - name: "imoveis"
    label: "Imóveis"
    folder: "content/imoveis"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Preço", name: "price", widget: "number" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Localização", name: "location", widget: "string" }
      - {
          label: "Características",
          name: "features",
          widget: "list",
          field: { label: "Item", name: "item", widget: "string" },
        }

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Imagem de Destaque", name: "cover", widget: "image" }
