#!/bin/bash
# Script baseado no guia completo - FileZilla Settings

echo "🔧 CONFIGURAÇÃO FILEZILLA PARA CORREÇÃO SUPHP"
echo "=============================================="

echo ""
echo "📋 DADOS DE CONEXÃO LOCAWEB (CORRETOS):"
echo "TENTE ESTES SERVIDORES FTP (EM ORDEM):"
echo "1. ftp.[seudominio].com.br (substitua pelo seu domínio)"
echo "2. 187.45.193.173 (IP direto)"
echo "3. ftp.locaweb.com.br"
echo "4. [servidor].locaweb.com.br"
echo ""
echo "CONFIGURAÇÕES FILEZILLA:"
echo "- Criptografia: 'Usar FTP simples (inseguro)'"
echo "- Modo de transferência: Passivo"
echo "- Porta: 21"
echo ""
echo "Porta: 21 (ou 22 para SFTP)"
echo "Usuário: [nome_da_sua_conta_locaweb]"
echo "Senha: [senha_do_painel_locaweb]"
echo "Tipo: FTP Normal (ou SFTP se porta 22)"

echo ""
echo "📁 DIRETÓRIO ALVO:"
echo "Procure por: /public_html/ ou /html/ ou /"
echo "Deve conter: index.php, wp-config.php, wp-content/"

echo ""
echo "🔧 CORREÇÃO DE PERMISSÕES (CRITICAL):"
echo "======================================"
echo "1. Selecionar TODOS os arquivos (Ctrl+A)"
echo "2. Botão direito → 'Permissões de arquivo...'"
echo ""
echo "CONFIGURAR:"
echo "┌─────────────────────────────────────┐"
echo "│ 📁 Diretórios  → 755 (rwxr-xr-x)   │"
echo "│ 📄 Arquivos    → 644 (rw-r--r--)   │"
echo "│ 🔒 wp-config   → 600 (rw-------)   │"
echo "└─────────────────────────────────────┘"
echo ""
echo "✅ Marcar: 'Aplicar a diretórios'"
echo "✅ Marcar: 'Aplicar a arquivos'"
echo "✅ Marcar: 'Recursivo'"

echo ""
echo "🧪 TESTE IMEDIATO:"
echo "curl -I http://portal.imobiliariaipe.com.br"
echo "Esperado: HTTP/1.1 200 OK"

echo ""
echo "💡 Se der erro de conexão FTP, tente:"
echo "- ftp.seudominio.com.br"
echo "- Porta 22 (SFTP)"
echo "- Porta 990 (FTPS)"