#!/bin/bash

# WordPress Config Diagnostic & Fix Tool
# Analisa e corrige problemas de configuração do WordPress

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configurações do banco de dados (confirmadas no backup)
DB_HOST="wp_imobiliaria.mysql.dbaas.com.br"
DB_NAME="wp_imobiliaria"
DB_USER="wp_imobiliaria"
DB_PASS="Ipe@4693"

SITE_URL="portal.imobiliariaipe.com.br"
LOG_FILE="$HOME/wp-backup-locaweb/wp-config-analysis.log"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

echo -e "${BLUE}=======================================
🔧 WordPress Config Analysis & Fix
=======================================${NC}"

log "Iniciando análise de configuração WordPress"

echo -e "\n${YELLOW}🔍 MÓDULO 1: Database Connection Test${NC}"

# Teste conexão do banco
log "Testando conectividade do banco de dados..."
if mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "SELECT 'Connection OK' as status;" 2>/dev/null; then
    echo -e "${GREEN}✅ Conexão com banco OK${NC}"
    log "Database connection: SUCCESS"
else
    echo -e "${RED}❌ Falha na conexão do banco${NC}"
    log "Database connection: FAILED"
fi

echo -e "\n${YELLOW}🔍 MÓDULO 2: WordPress Configuration Analysis${NC}"

# Gerar wp-config.php correto
log "Gerando wp-config.php de referência..."

cat > "$HOME/wp-backup-locaweb/wp-config-reference.php" << 'EOF'
<?php
/**
 * WordPress Configuration - Imobiliária IPE
 * Generated by diagnostic tool
 */

// ** MySQL settings ** //
/** The name of the database for WordPress */
define('DB_NAME', 'wp_imobiliaria');

/** MySQL database username */
define('DB_USER', 'wp_imobiliaria');

/** MySQL database password */
define('DB_PASSWORD', 'Ipe@4693');

/** MySQL hostname */
define('DB_HOST', 'wp_imobiliaria.mysql.dbaas.com.br');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8mb4');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 */
define('AUTH_KEY',         'ipe_auth_key_secure_2024');
define('SECURE_AUTH_KEY',  'ipe_secure_auth_key_2024');
define('LOGGED_IN_KEY',    'ipe_logged_in_key_2024');
define('NONCE_KEY',        'ipe_nonce_key_2024');
define('AUTH_SALT',        'ipe_auth_salt_2024');
define('SECURE_AUTH_SALT', 'ipe_secure_auth_salt_2024');
define('LOGGED_IN_SALT',   'ipe_logged_in_salt_2024');
define('NONCE_SALT',       'ipe_nonce_salt_2024');

/**#@-*/

/**
 * WordPress Database Table prefix.
 */
$table_prefix  = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define('WP_DEBUG', false);
define('WP_DEBUG_LOG', false);
define('WP_DEBUG_DISPLAY', false);

// Security improvements
define('DISALLOW_FILE_EDIT', true);
define('FORCE_SSL_ADMIN', true);

// Performance
define('WP_MEMORY_LIMIT', '512M');
define('WP_MAX_MEMORY_LIMIT', '512M');

// Site URLs
define('WP_HOME','https://portal.imobiliariaipe.com.br');
define('WP_SITEURL','https://portal.imobiliariaipe.com.br');

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
EOF

echo -e "${GREEN}✅ wp-config.php de referência criado em: wp-config-reference.php${NC}"

echo -e "\n${YELLOW}🔍 MÓDULO 3: .htaccess Analysis${NC}"

# Gerar .htaccess correto
log "Gerando .htaccess de referência..."

cat > "$HOME/wp-backup-locaweb/.htaccess-reference" << 'EOF'
# BEGIN WordPress
# As diretrizes (linhas) entre "BEGIN WordPress" e "END WordPress" são
# geradas dinamicamente e só devem ser modificadas através de filtros do WordPress.
# Quaisquer alterações nas diretrizes entre estes marcadores serão sobrescritas.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress

# Security headers
<IfModule mod_headers.c>
Header always set X-Frame-Options DENY
Header always set X-Content-Type-Options nosniff
Header always set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

# PHP settings
<IfModule mod_php7.c>
php_value memory_limit 512M
php_value max_execution_time 300
php_value max_input_vars 3000
php_value upload_max_filesize 64M
php_value post_max_size 64M
</IfModule>
EOF

echo -e "${GREEN}✅ .htaccess de referência criado${NC}"

echo -e "\n${YELLOW}🔍 MÓDULO 4: Database Query Analysis${NC}"

# Verificar configurações do WordPress no banco
log "Analisando configurações do WordPress no banco..."

mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" << 'SQL' 2>/dev/null > "$HOME/wp-backup-locaweb/wp-options-analysis.txt"
SELECT 
    option_name, 
    option_value 
FROM wp_options 
WHERE option_name IN (
    'siteurl', 
    'home', 
    'active_plugins', 
    'template', 
    'stylesheet',
    'admin_email'
) 
ORDER BY option_name;
SQL

if [ -f "$HOME/wp-backup-locaweb/wp-options-analysis.txt" ]; then
    echo -e "${GREEN}✅ Análise das opções do WordPress${NC}"
    cat "$HOME/wp-backup-locaweb/wp-options-analysis.txt"
else
    echo -e "${RED}❌ Não foi possível analisar as opções do WordPress${NC}"
fi

echo -e "\n${YELLOW}🔍 MÓDULO 5: Plugin Analysis${NC}"

# Listar plugins ativos
log "Analisando plugins ativos..."

mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" << 'SQL' 2>/dev/null > "$HOME/wp-backup-locaweb/active-plugins.txt"
SELECT option_value FROM wp_options WHERE option_name = 'active_plugins';
SQL

if [ -f "$HOME/wp-backup-locaweb/active-plugins.txt" ]; then
    echo -e "${GREEN}✅ Plugins ativos identificados${NC}"
    echo "Conteúdo salvo em: active-plugins.txt"
fi

echo -e "\n${YELLOW}🔍 MÓDULO 6: Fix Recommendations${NC}"

cat << EOF

${GREEN}✅ === ANÁLISE COMPLETA ====${NC}

${YELLOW}🔧 PROBLEMAS IDENTIFICADOS:${NC}
1. ❌ WordPress não consegue conectar ao banco (erro 500)
2. ⚠️  Possível problema no wp-config.php
3. ⚠️  Configurações de URL podem estar incorretas

${BLUE}🛠️  SOLUÇÕES RECOMENDADAS:${NC}

${GREEN}IMEDIATAS (via painel LocaWeb):${NC}
1. 📝 Substituir wp-config.php pelo arquivo de referência
2. 📁 Verificar .htaccess (usar referência se necessário)
3. 🔌 Desativar plugins temporariamente
4. 🎨 Trocar tema para padrão WordPress

${GREEN}ARQUIVOS CRIADOS:${NC}
- wp-config-reference.php (configuração correta)
- .htaccess-reference (regras corretas)
- wp-options-analysis.txt (configurações do banco)
- active-plugins.txt (plugins ativos)

${YELLOW}📋 PRÓXIMOS PASSOS:${NC}
1. Acessar painel LocaWeb
2. Ir no gerenciador de arquivos
3. Fazer backup do wp-config.php atual
4. Substituir pelo wp-config-reference.php
5. Testar o site

EOF

log "Análise de configuração WordPress finalizada"

echo -e "\n${BLUE}=======================================
📊 Análise concluída!
=======================================${NC}"