// Core Components - Only exporting what actually exists
export { default as AdvancedDropdown } from './AdvancedDropdown';
export { default as AnimatedCTASection } from './AnimatedCTASection';
export { default as AnimatedStatsCard } from './AnimatedStatsCard';
export { default as AnuncioNovaVersao } from './AnuncioNovaVersao';
export { default as Badge } from './badge';
export { default as BlocoCTAConversao } from './BlocoCTAConversao';
export { default as BlocoLocalizacaoImovel } from './BlocoLocalizacaoImovel';
export { default as Button, buttonVariants } from './button';
export { default as Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent } from './card';
export { default as CardCTAImovel } from './CardCTAImovel';
export { default as Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from './carousel';
export { default as ChunkErrorBoundary } from './ChunkErrorBoundary';
export { default as CleanPropertySections, CleanSalesSection, CleanRentalsSection } from './CleanPropertySections';
export { default as ClientComponents, ClientOnly, useProperties, FilterTagsDisplay, QuickPropertySearch } from './ClientComponents';
export { default as ClientPage } from './ClientPage';
export { default as ClientPerformanceMonitor } from './ClientPerformanceMonitor';
export { default as DebugTools } from './debug-tools';
export { default as DynamicOGGenerator } from './DynamicOGGenerator';
export { default as EmptyState } from './EmptyState';
export { default as EnhancedImage } from './EnhancedImage';
export { default as EnhancedNotificationBanner } from './EnhancedNotificationBanner';
export { default as EnhancedPropertyCard } from './EnhancedPropertyCard';
export { default as EnhancedPropertySection } from './EnhancedPropertySection';
export { default as EnhancedPropertySections, EnhancedSalesSection, EnhancedRentalsSection, CombinedPropertySections } from './EnhancedPropertySections';
export { default as EnhancedTestimonials } from './EnhancedTestimonials';
export { default as ErrorBoundary } from './ErrorBoundary';
export { default as ErrorBoundaryComponents, ErrorFallback, LoadingFallback, HeroLoadingFallback, PropertyLoadingFallback } from './ErrorBoundaryComponents';
export { default as ErrorState } from './ErrorState';
export { default as FallbackPropertyCard } from './FallbackPropertyCard';
export { default as FramerMotionWrapper } from './FramerMotionWrapper';
export { default as HeroAdapter } from './HeroAdapter';
export { default as HeroClient } from './HeroClient';
export { default as HeroImovel } from './HeroImovel';
export { default as HeroImovelSimbolico } from './HeroImovelSimbolico';
export { default as HeroInstitucional } from './HeroInstitucional';
export { default as ImageOptimizations } from './ImageOptimizations';
export { default as ImoveisAluguelComponents, LoadingState, ErrorState as ImoveisErrorState, EmptyState as ImoveisEmptyState, CarouselCard, ImovelHero as ImoveisImovelHero } from './ImoveisAluguelComponents';
export { default as ImoveisCarousel } from './ImoveisCarousel';
export { default as ImoveisDestaqueContext, useImoveisDestaque } from './ImoveisDestaqueContext';
export { default as ImovelCard } from './ImovelCard';
export { default as ImovelHero } from './ImovelHero';
export { default as InViewObserver } from './InViewObserver';
export { default as IpeConcept } from './ipeConcept';
export { default as IpeConceptRefactored } from './IpeConceptRefactored';
export { default as LayoutClientOptimized } from './LayoutClientOptimized';
export { default as LazyLoader } from './LazyLoader';
export { default as LoadingGrid } from './LoadingGrid';
export { default as LucidePreloader } from './LucidePreloader';
export { default as MobilePropertyCard } from './MobilePropertyCard';
export { default as MobilePropertyCarousel } from './MobilePropertyCarousel';
export { default as NoSSR } from './NoSSR';
export { default as NotificacaoBanner } from './NotificacaoBanner';
export { default as OptimizationProvider } from './OptimizationProvider';
export { default as OptimizedCarousel } from './OptimizedCarousel';
export { default as OptimizedImage } from './OptimizedImage';
export { default as OptimizedImageGallery } from './OptimizedImageGallery';
export { default as OptimizedImagePlaceholder, useSafePlaceholderUrl } from './OptimizedImagePlaceholder';
export { default as OptimizedImovelCard } from './OptimizedImovelCard';
export { default as PageStaticData } from './page-static-data';
export { default as PremiumPropertyCatalog } from './PremiumPropertyCatalog';
export { default as PropertyAdapter } from './PropertyAdapter';
export { default as PropertyCard } from './PropertyCard';
export { default as PropertyCardUnified } from './PropertyCardUnified';
export { default as PropertyCarousel } from './PropertyCarousel';
export { default as PropertyCatalog } from './PropertyCatalog';
export { default as PropertyContactModal } from './PropertyContactModal';
export { default as PropertyDetails } from './PropertyDetails';
export { default as PropertyFeaturesUnified } from './PropertyFeaturesUnified';
export { default as PropertyFeatureTabs } from './PropertyFeatureTabs';
export { default as PropertyFilters } from './PropertyFilters';
export { default as PropertyHero } from './PropertyHero';
export { default as PropertyHeroUnified } from './PropertyHeroUnified';
export { default as PropertyImage } from './PropertyImage';
export { default as PropertySearch } from './PropertySearch';
export { default as PropertySection } from './PropertySection';
export { default as PropertySectionLayout } from './PropertySectionLayout';
export { default as PropertyShowcase } from './PropertyShowcase';
export { default as PropertyShowcaseAdapter } from './PropertyShowcaseAdapter';
export { default as PropertyShowcaseSystem } from './PropertyShowcaseSystem';
export { default as PropertySocialSharing } from './PropertySocialSharing';
export { default as PropertySort } from './PropertySort';
export { default as ReferencesSection } from './ReferencesSection';
export { default as SafeFramerWrapper } from './SafeFramerWrapper';
export { default as SafeHydration } from './SafeHydration';
export { default as SafeIcon, createSafeIcon, SafeHomeIcon, SafeSettingsIcon, SafeUserIcon, SafeMenuIcon, SafeXIcon, SafeCheckIcon } from './SafeIcon';
export { default as SafeSuspenseWrapper } from './SafeSuspenseWrapper';
export { default as ScrollAnimations } from './ScrollAnimations';
export { default as SectionHeader } from './SectionHeader';
export { default as SkeletonLoader } from './SkeletonLoader';
export { default as SkipToContent } from './SkipToContent';
export { default as SocialShareButtons } from './SocialShareButtons';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as ThemeToggle } from './ThemeToggle';
export { default as ThirdPartyScriptLoader, defaultScripts } from './ThirdPartyScriptLoader';
export { default as Toast } from './toast';
export { default as TrustAndCredibilitySectionClient } from './TrustAndCredibilitySection.client';
export { default as TrustAndCredibilitySectionServer } from './TrustAndCredibilitySection.server';
export { default as UnifiedComponents } from './UnifiedComponents';
export { default as UnifiedLoading } from './UnifiedLoading';
export { default as VirtualizedPropertiesGrid } from './VirtualizedPropertiesGrid';
export { default as VirtualizedPropertiesGridUnified } from './VirtualizedPropertiesGridUnified';
export { default as VirtualTourViewer } from './VirtualTourViewer';
export { default as WebVitals } from './WebVitals';
export { default as WebVitalsDebuggerWrapper } from './WebVitalsDebuggerWrapper';
export { default as WebVitalsMonitor } from './WebVitalsMonitor';
export { default as WhatsAppButton } from './WhatsAppButton';
export { default as WhatsAppMetaTags } from './WhatsAppMetaTags';
export { default as WhatsAppOptimizer } from './WhatsAppOptimizer';
export { default as WhatsAppPreviewCard } from './WhatsAppPreviewCard';
export { default as WhatsAppShare } from './WhatsAppShare';
export { default as WhatsAppSharingOptimizer } from './WhatsAppSharingOptimizer';
